name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  my-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i -p --frozen-lockfile

      - name: Run tests
        run: bun test
